apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jeet-14/CISION'
    targetRevision: HEAD
    path: 'charts/my-chart'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
