FROM nginx:1.19
RUN apt-get update -y && apt-get upgrade --no-install-recommends -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
LABEL description="this is enhanced version of base image of nginx:1.19" author="www.linkedin.com/in/jeet14"
